import type { Metadata } from 'next'
import { Roboto, Baloo_2 } from 'next/font/google'
import './globals.css'

const roboto = Roboto({ subsets: ['latin'], weight: ['400', '700'], variable: '--font-roboto' })
const baloo = Baloo_2({ subsets: ['latin'], weight: ['700', '800'], variable: '--font-baloo' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className={`${roboto.variable} ${baloo.variable}`} lang="pt">
      <body className='bg-base-title'>
        {children}
      </body>
    </html>
  )
}
